# Generated by Django 3.0.3 on 2020-05-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0004_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
