# Generated by Django 3.0.3 on 2020-05-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0005_activity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
    ]
